export const randomProductNames = [
    "Quantum X1 Smartphone",
    "EchoSound Pro Bluetooth Earbuds",
    "VoltCharge 20W Wireless Charger",
    "Chronos Fit S3 Smartwatch",
    "Matrix Click Mechanical Keyboard",
    "WaveBlast Mini Speaker",
    "UrbanStyle Egyptian Cotton T-Shirt",
    "Slim Flex Fit Jeans",
    "AeroPace Run Running Shoes",
    "StormShield Windbreaker Jacket",
    "SunGlow Classic Sunglasses",
    "LeatherVibe Crossbody Bag",
    "HidraGlow Vitamin C Facial Serum",
    "BioKeratin Repairing Shampoo",
    "SunBlocker SPF 60 Sunscreen",
    "Velvet Skin Moisturizing Cream",
    "Lumina Deo Parfum 100ml",
    "NutriOils Hair Mask",
    "Touch Minimalist Desk Lamp",
    "SoftTouch 400 Thread Count Sheet Set",
    "Express Aroma Electric Coffee Maker",
    "Urban Deco Velvet Throw Pillow",
    "Cyclone 2000 Stick Vacuum Cleaner",
    "ClearBox Acrylic Organizer"
];
