import fs from 'fs';
import path from 'path';
import { SCRIPTS_CONFIG } from './config';
import { StoryIndexedInfo, StoryIndexedSection } from './models/story-indexed-info';
import { getRelativePath } from './utils/get-relative-path';
import { kebabToPascalCase } from './utils/kebab-to-pascal-case';
import { StoryFileScrapper } from './utils/story-file-scrapper';

interface AiDocsPage {
    id: string;
    title: string;
    route: string;
    outputPath: string;
    content: string;
}

interface ExampleFile {
    name: string;
    language: 'typescript' | 'html' | 'css';
    content: string;
}

type ExamplesByComponent = Map<string, ExampleFile[]>;

const GENERATED_NOTICE = '<!-- This file is generated by scripts/generate-ai-docs.ts. Do not edit manually. -->';

const normalizePath = (value: string) => value.replaceAll('\\', '/');

const ensureDirectory = (directory: string) => {
    fs.mkdirSync(directory, { recursive: true });
};

const writeTextFile = (file: string, content: string) => {
    ensureDirectory(path.dirname(file));
    fs.writeFileSync(file, content);
};

const cleanMarkdown = (content: string) => {
    return content
        .replace(/<story-meta\s+[^>]*\/>\s*/g, '')
        .trim();
};

const fencedLanguage = (language: ExampleFile['language']) => {
    if (language === 'typescript') return 'ts';
    if (language === 'html') return 'html';
    return 'css';
};

const getPublicUrl = (file: string) => {
    const relativePath = normalizePath(path.relative(SCRIPTS_CONFIG.general.assetsFolder, file));

    return `${SCRIPTS_CONFIG.general.baseUrl}${relativePath}`;
};

const getStoryDocumentationFile = (file: string) => {
    if (file.endsWith('.docs.md')) return file;

    const docFile = file.replace('.stories.ts', '.docs.md');

    return fs.existsSync(docFile) ? docFile : null;
};

const readDocumentation = (file: string) => {
    const docFile = getStoryDocumentationFile(file);

    if (!docFile) return '';

    return cleanMarkdown(fs.readFileSync(docFile, 'utf8'));
};

const compareExampleFiles = (a: ExampleFile, b: ExampleFile) => {
    const order = {
        typescript: 0,
        html: 1,
        css: 2,
    };

    return order[a.language] - order[b.language] || a.name.localeCompare(b.name);
};

const getExampleLanguage = (fileName: string): ExampleFile['language'] => {
    if (fileName.endsWith('.ts')) return 'typescript';
    if (fileName.endsWith('.html')) return 'html';

    return 'css';
};

const getExamples = (storyFile: string): ExamplesByComponent => {
    const relativePath = getRelativePath(storyFile);
    const storyFolder = path.dirname(relativePath);
    const examplesDirectory = path.resolve(
        SCRIPTS_CONFIG.general.storiesFolder,
        storyFolder,
        'examples'
    );
    const result: ExamplesByComponent = new Map();

    if (!fs.existsSync(examplesDirectory)) return result;

    const files = fs.readdirSync(examplesDirectory, {
        recursive: true,
        withFileTypes: true,
    });

    files
        .filter((file) => {
            return (
                file.isFile() &&
                (file.name.endsWith('.component.ts') ||
                    file.name.endsWith('.component.html') ||
                    file.name.endsWith('.component.scss'))
            );
        })
        .forEach((file) => {
            const componentKey = kebabToPascalCase(
                file.name
                    .replace('.component.ts', '-component')
                    .replace('.component.html', '-component')
                    .replace('.component.scss', '-component')
            );
            const current = result.get(componentKey) ?? [];
            const filePath = path.join(file.parentPath, file.name);

            current.push({
                name: file.name,
                language: getExampleLanguage(file.name),
                content: fs.readFileSync(filePath, 'utf8').trim(),
            });

            result.set(componentKey, [...current].sort(compareExampleFiles));
        });

    return result;
};

const getImportStatement = (story: StoryIndexedInfo) => {
    if (story.meta.type !== 'story' || !story.meta.componentName) return null;

    return `import { ${story.meta.componentName} } from 'frakton-ng/${story.meta.id}';`;
};

const pushMetadata = (lines: string[], story: StoryIndexedInfo) => {
    lines.push('## Metadata');
    lines.push('');
    lines.push(`- id: ${story.meta.id}`);
    lines.push(`- type: ${story.meta.type}`);
    lines.push(`- route: /docs/${story.meta.id}`);
    lines.push(`- title: ${story.meta.title}`);

    if (story.meta.componentName) {
        lines.push(`- component: ${story.meta.componentName}`);
    }

    const importStatement = getImportStatement(story);

    if (importStatement) {
        lines.push(`- import: \`${importStatement}\``);
    }

    lines.push('');
};

const pushDescription = (lines: string[], story: StoryIndexedInfo) => {
    if (!story.meta.description) return;

    lines.push('## Description');
    lines.push('');
    lines.push(story.meta.description.trim());
    lines.push('');
};

const pushExampleFiles = (
    lines: string[],
    section: StoryIndexedSection,
    examples: ExamplesByComponent
) => {
    const componentName = section.componentName || `${section.name}Component`;
    const files = examples.get(componentName);

    if (!files?.length) return;

    lines.push('');
    lines.push(`Example component: \`${componentName}\``);

    files.forEach((file) => {
        lines.push('');
        lines.push(`\`\`\`${fencedLanguage(file.language)} title="${file.name}"`);
        lines.push(file.content);
        lines.push('```');
    });
};

const pushFeatureSections = (
    lines: string[],
    story: StoryIndexedInfo,
    examples: ExamplesByComponent
) => {
    if (story.meta.type !== 'story' || story.sections.length === 0) return;

    lines.push('## Features');
    lines.push('');

    story.sections.forEach((section) => {
        const level = Math.max(section.level ?? 3, 3);

        lines.push(`${'#'.repeat(level)} ${section.name}`);
        lines.push('');
        lines.push(`- id: ${section.id}`);
        lines.push(`- type: ${section.type}`);

        if (section.componentName) {
            lines.push(`- component: ${section.componentName}`);
        }

        if (section.description) {
            lines.push('');
            lines.push(section.description.trim());
        }

        if (section.type === 'story') {
            pushExampleFiles(lines, section, examples);
        }

        lines.push('');
    });
};

const pushApiReference = (lines: string[], documentation: string) => {
    if (!documentation) return;

    lines.push('## API Reference');
    lines.push('');
    lines.push(documentation);
    lines.push('');
};

const generatePageMarkdown = (file: string, story: StoryIndexedInfo) => {
    const lines = [GENERATED_NOTICE, '', `# ${story.meta.title}`, ''];
    const examples = story.meta.type === 'story' ? getExamples(file) : new Map();
    const documentation = readDocumentation(file);

    pushMetadata(lines, story);
    pushDescription(lines, story);
    pushFeatureSections(lines, story, examples);
    pushApiReference(lines, documentation);

    return `${lines.join('\n').trim()}\n`;
};

const generateShortIndex = (pages: AiDocsPage[]) => {
    const lines = [
        GENERATED_NOTICE,
        '',
        '# Frakton NG Documentation',
        '',
        'This file lists the generated Markdown documentation files intended for AI indexing and retrieval.',
        '',
        `- Full documentation: ${SCRIPTS_CONFIG.general.baseUrl}llms-full.md`,
        '',
        '## Pages',
        '',
    ];

    pages.forEach((page) => {
        lines.push(`- [${page.title}](${getPublicUrl(page.outputPath)})`);
        lines.push(`  - id: ${page.id}`);
        lines.push(`  - route: ${page.route}`);
    });

    return `${lines.join('\n')}\n`;
};

const generateFullMarkdown = (pages: AiDocsPage[]) => {
    const lines = [
        GENERATED_NOTICE,
        '',
        '# Frakton NG Documentation',
        '',
        'This file concatenates the generated per-page Markdown documentation for AI indexing and retrieval.',
        '',
    ];

    pages.forEach((page) => {
        lines.push(`<!-- Source: /llms/${page.id}.md -->`);
        lines.push('');
        lines.push(page.content.replace(GENERATED_NOTICE, '').trim());
        lines.push('');
        lines.push('---');
        lines.push('');
    });

    return `${lines.join('\n').trim()}\n`;
};

export const generateAiDocs = (scrapper: StoryFileScrapper) => {
    const outputDirectory = path.join(SCRIPTS_CONFIG.general.assetsFolder, 'llms');
    const pages = scrapper
        .getAll()
        .map(({ path: file, story }): AiDocsPage => {
            const content = generatePageMarkdown(file, story);
            const outputPath = path.join(outputDirectory, `${story.meta.id}.md`);

            return {
                id: story.meta.id,
                title: story.meta.title,
                route: `/docs/${story.meta.id}`,
                outputPath,
                content,
            };
        })
        .sort((a, b) => a.title.localeCompare(b.title));

    fs.rmSync(outputDirectory, { recursive: true, force: true });
    ensureDirectory(outputDirectory);

    pages.forEach((page) => {
        writeTextFile(page.outputPath, page.content);
    });

    writeTextFile(
        path.join(SCRIPTS_CONFIG.general.assetsFolder, 'llms.txt'),
        generateShortIndex(pages)
    );
    writeTextFile(
        path.join(SCRIPTS_CONFIG.general.assetsFolder, 'llms-full.md'),
        generateFullMarkdown(pages)
    );
};
